replicaCount: 3

image:
  repository: zemlianin/sum-app
  pullPolicy: Always
  tag: latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: NodePort
  ports:
    http: 8080
    grpc: 9090

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

livenessProbe:
  httpGet:
    path: /rates
    port: 8080
readinessProbe:
  httpGet:
    path: /rates
    port: 8080

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}

extraEnv:
  - name: DB_HOST
    value: localhost
  - name: DB_PORT
    value: "5432"
  - name: DB_NAME
    value: stage
  - name: DB_USER
    value: postgres
  - name: DB_PASSWORD
    value: 1Q2w3e4r5t
  - name: CONVERTER_URL
    value: http://localhost:8081
  - name: KEYCLOAK_URL
    value: http://194.87.186.59:8080
  - name: RATE_URL
    value: http://localhost:8080
  - name: KEYCLOAK_REALM
    value: auth
  - name: CLIENT_ID
    value: dwh-manager
  - name: CLIENT_SECRET
    value: zThmHP3m3Wl5QIscj7t3Nf9ZOyAOPTRz
  - name: NOTIFICATION_SERVICE_URL
    value: http://rates:8080