apiVersion: v1
kind: Service
metadata:
  name: {{ include "sum-app.fullname" . }}
  labels:
    {{- include "sum-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.http }}
      targetPort: 8080
      protocol: TCP
      name: http
    - port: {{ .Values.service.ports.grpc }}
      targetPort: 9090
      protocol: TCP
      name: grpc
  selector:
    {{- include "sum-app.selectorLabels" . | nindent 4 }}
