name: Autotests-hw4

on:
  workflow_call:
    inputs:
      chart-path:
        required: true
        type: string
      converter-image-name:
        required: true
        type: string
      accounts-image-name:
        required: true
        type: string
      image-tag:
        required: true
        type: string

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/checkout@v4
        with:
          repository: central-university-dev/hse-autotests
          ref: main
          path: tests


      - name: Start minikube
        uses: medyagh/setup-minikube@master

      - name: Add helm repo
        run: |
          helm repo add cetic https://cetic.github.io/helm-charts
          helm repo add codecentric https://codecentric.github.io/helm-charts
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo update



      - name: Deploy postgres
        continue-on-error: true
        run: |
          helm install postgresql bitnami/postgresql -f tests/hw4/postgres-values.yml --wait --timeout 180s

      - name: Deploy keycloak
        continue-on-error: true
        run: |
          kubectl create secret generic realm-secret --from-file=tests/hw4/realm.json
          helm install keycloak codecentric/keycloakx -f tests/hw4/keycloak-values.yml --wait --timeout 180s


      - name: Deploy rates
        continue-on-error: true
        run: |
          helm upgrade --install rates ${{ inputs.chart-path }} \
            --set fullnameOverride=rates \
            --set image.repository=miraclewisp/hse-rates \
            --set image.tag=auth-amd64 \
            -f tests/hw4/rates-values.yml \
            --wait --timeout 180s

      - name: Deploy converter
        continue-on-error: true
        run: |
          helm upgrade --install converter ${{ inputs.chart-path }} \
            --set fullnameOverride=converter \
            --set image.repository=${{ inputs.converter-image-name }} \
            --set image.tag=${{ inputs.image-tag }} \
            -f tests/hw4/converter-values.yml \
            --wait --timeout 180s

      - name: Deploy accounts
        continue-on-error: true
        run: |
          helm upgrade --install accounts ${{ inputs.chart-path }} \
            --set fullnameOverride=accounts \
            --set image.repository=${{ inputs.accounts-image-name }} \
            --set image.tag=${{ inputs.image-tag }} \
            -f tests/hw4/accounts-values.yml \
            --wait --timeout 180s

      - name: Run tests
        continue-on-error: true
        run: |
          helm install autotest cetic/job \
            --set image.repository=miraclewisp/hse-accounts-test \
            --set image.tag=amd64 \
            --set backoffLimit=0 \
            -f tests/hw4/test-values.yml \
            --wait --wait-for-jobs --timeout 180s

      - name: Debug k8s entities
        run: |
          kubectl get deployments
          kubectl get pods
          kubectl get services


      - name: Debug logs
        run: |
          kubectl get pods -n default|grep -v NAME|awk '{print $1}'|while read pods;do kubectl logs $pods;echo;done      

      - name: Get test logs
        run: |
          kubectl logs jobs/autotest-job
          ERROR_LOGS=$(kubectl logs jobs/autotest-job | grep 'ERROR |' || true)
          echo "JOB_ERRORS<<EOF" >> $GITHUB_ENV
          echo "$ERROR_LOGS" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - uses: actions/github-script@v7
        with:
          script: |
            const errors = process.env.JOB_ERRORS
            let body = ""
            if (errors) {
              body = `### ❌ Ошибки \n\n ${errors}`
            } else {
              body = `### ✅ Тесты пройдены`
            }
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            })
