name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t sum-app:${GITHUB_REF##*/}-${GITHUB_SHA:0:7} .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Push Docker image
        run: docker push myapp:${GITHUB_REF##*/}-${GITHUB_SHA:0:7}

      - name: Tag Docker image as latest (if on master)
        if: github.ref == 'refs/heads/master'
        run: docker tag sum-app:${GITHUB_REF##*/}-${GITHUB_SHA:0:7} sum-app:latest && docker push sum-app:latest
