name: CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          IMAGE_TAG=${GITHUB_REF##*/}-${GITHUB_SHA:0:7}
          echo "::set-output name=image_tag::$IMAGE_TAG"
          docker build -t zemlianin/sum-app:$IMAGE_TAG .
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker push zemlianin/sum-app:${GITHUB_REF##*/}-${GITHUB_SHA:0:7}
        
      - name: Double push image
        run: docker push zemlianin/sum-app:latest

      - name: Tag Docker image as latest
        if: github.ref == 'refs/heads/main'
        run: |
          docker tag zemlianin/sum-app:${{ steps.set-image-tag.outputs.image_tag }} zemlianin/sum-app:latest
          docker push zemlianin/sum-app:latest
      
  autotest:
    needs: build # имя вашей основной джобы сборки
    uses: ./.github/workflows/autotests-hw4.yml
    with:
      chart-path: ./sum-app # путь к чарту из второй дз
      converter-image-name: zemlianin/converter # имя образа вашего приложения
      accounts-image-name: zemlianin/accounts # имя образа вашего приложения
      image-tag: latest # таг образа, который собран в рамках данного ПРа
    secrets:
      HSE_LOKI_TOKEN: ${{ secrets.HSE_LOKI_TOKEN }}

